baseURL = 'http://david.krentzlin.me/'
languageCode = 'en-us'
title = 'David Krentzlin'
theme = 'anatole'

enableEmoji = true
enableRobotsTXT = true

[params]
title = "David Krentzlin"
description = "Show up. Do the work. Finish strong."
profilePicture = "images/profile.jpg"
doNotLoadAnimations = true
copyright = "David Krentzlin {{ YEAR }}"

[[menu.main]]
    name = "home"
    url = "/home/"
    weight = 1

[[menu.main]]
    name = "Professional"
    url = "/portfolio/"
    weight = 5

[[params.socialIcons]]
	title = "github"
	url = "https://github.com/certainty"
  icon = "fab fa-github"
  network = ""

[[params.socialIcons]]
	title = "twitter"
	url = "https://twitter.com/certainty"
  icon = "fab fa-twitter-square"

[[params.socialIcons]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/david-krentzlin-b1708818b/"
  icon = "fab fa-linkedin"

[[params.socialIcons]]
	title = "email"
	url = "mailto:david.krentzlin@gmail.com"
  icon = "fas fa-envelope-square"

[mermaid]
 enable = true
